### ISSUE TITLE
Papercuts

### ISSUE THREAD

**Issue by tchx84** [flathub/org.sugarlabs.MathHurdler#5]
A few things that slip through the review:

- [x] Restore the original license
- [x] Improve the summary
- [x] Separate monitors patch from regular port patch.
- [x] Rename appdata to metainfo.

**Comment by SudoSu-bham** [comment]
Restoring original license would cause Linter error in flathub. Flathub was not accepting `License = MIT License`.

**Comment by SudoSu-bham** [comment]
appdata.xml is already renamed to metainfo.xml. Are you referring to some other appdata?

**Comment by tchx84** [comment]
> appdata.xml is already renamed to metainfo.xml. Are you referring to some other appdata?

@SudoSu-bham can you check the other (new) apps? I might have noticed these in another, but ended up putting the comments here instead.
